<?php

namespace AppBundle\Repository;

/**
 * CompradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompradorRepository extends \Doctrine\ORM\EntityRepository
{
}
