<?php

namespace AppBundle\Repository;

/**
 * DestinatarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinatarioRepository extends \Doctrine\ORM\EntityRepository
{
}
