<?php

namespace AppBundle\Repository;

/**
 * RegaloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegaloRepository extends \Doctrine\ORM\EntityRepository
{
}
