<?php

namespace AppBundle\Repository;

/**
 * TiendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiendaRepository extends \Doctrine\ORM\EntityRepository
{
}
