# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.regalo:
        class: AppBundle\Admin\RegaloAdmin
        arguments: [~, AppBundle\Entity\Regalo, AppBundle:RegaloAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Activos }
        calls:
            - [ setTemplate, [edit, :Admin:edit_regalo.html.twig]]
    admin.regalo_pasado:
        class: AppBundle\Admin\RegaloPasadoAdmin
        arguments: [~, AppBundle\Entity\Regalo, AppBundle:RegaloPasadoAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Pasados }

